### ISSUE TITLE
How do I put my navigation in vertical direction

### ISSUE THREAD

**Issue by hoanganhduong** [hoanganhduong/web-design-2-independent-project#1]
<img width="1391" alt="Screen Shot 2020-12-04 at 2 07 18 PM" src="https://user-images.githubusercontent.com/55412298/101204581-71316e00-363a-11eb-95bc-fe30c2354fda.png">
I tried this for the .nav-check:checked ~ .list but still doesn't work
display: flex;
flex-direction: column / flex-wrap: wrap;

@JessJodoin @HannahDelaney @mackenzierose @hellachella

**Comment by JessJodoin** [comment]
It's not lining up how you want because the flex container has be put on the wrong element. To make them stack on top of each other, just move the `display: flex;` and `flex-direction: column;` in the main.css to the `<li>` instead
