### ISSUE TITLE
How can I add a gradient overlay to an image

### ISSUE THREAD

**Issue by hoanganhduong** [hoanganhduong/web-design-2-independent-project#2]
I tried linear-gradient but apparently, I used it in a wrong way
<img width="1647" alt="Screen Shot 2020-12-11 at 2 39 38 AM" src="https://user-images.githubusercontent.com/55412298/101876391-5428fd80-3b5a-11eb-8303-ab427dbbf873.png">
@JessJodoin @mackenzierose @HannahDelaney @hellachella

**Comment by JessJodoin** [comment]
There isn't really an easy way of doing this. It can be done but it's going to be a lot playing around. If you'd like to I can try and help figure it out. Or if you'd rather (to make it easier on yourself), you could add the gradient to the image in Photoshop and re-export it
